In [39]:
import math

import numpy

print(dir(math))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [40]:
print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


In [41]:
math.log(32, 2)

5.0

In [42]:
#alias
import math as mt
mt.pi

3.141592653589793

In [43]:
from math import *
print(round(pi, 3), log(32, 2))

3.142 5.0


In [44]:
from math import log, pi
from numpy import asarray, random
# https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.html

print(log(25, 5), round(pi, 4))
planet = 'Pluto'
a = [1, 2, 3]
asarray(a)

2.0 3.1416


array([1, 2, 3])

In [58]:
rolls = random.randint(low=1, high=6, size=10)
rolls.mean()
rolls

array([3, 3, 1, 4, 2, 1, 5, 2, 2, 2])

In [61]:
xlist = [[1,2,3],[2,4,6],]
# Create a 2-dimensional array
x = numpy.asarray(xlist)
print("xlist = {}".format(xlist))
print("x = {}".format(x))

xlist = [[1, 2, 3], [2, 4, 6]]
x = [[1 2 3]
 [2 4 6]]


In [62]:
# Get the last element of the second row of our numpy array
x[1,-1]

6

In [65]:
xlist[1][-1]

6

In [ ]:
# https://docs.python.org/3.4/reference/datamodel.html#special-method-names

In [66]:
def best_items(racers):
    winner_item_counts = {}
    for k in range(len(racers)):
        # The i'th racer dictionary
        racer = racers[k]
        # We're only interested in racers who finished in first
        if racer['finish'] == 1:
            for i in racer['items']:
                # Add one to the count for this item (adding it to the dict if necessary)
                if i not in winner_item_counts:
                    winner_item_counts[i] = 0
                winner_item_counts[i] += 1

        # Data quality issues :/ Print a warning about racers with no name set. We'll take care of it later.
        if racer['name'] is None:
            print("WARNING: Encountered racer with unknown name on iteration {}/{} (racer = {})".format(
                k+1, len(racers), racer['name'])
            )
    return winner_item_counts

data_set = [{'name': 'Peach', 'items': ['green shell', 'banana', 'green shell'], 'finish': 3}, {'name': 'Peach', 'items': ['green shell', 'banana', 'green shell'], 'finish': 1}, {'name': 'Bowser', 'items': ['green shell'], 'finish': 1}, {'name': None, 'items': ['green shell'], 'finish': 2}, {'name': 'Bowser', 'items': ['green shell'], 'finish': 1}, {'name': None, 'items': ['red shell'], 'finish': 1}, {'name': 'Yoshi', 'items': ['banana', 'blue shell', 'banana'], 'finish': 7}, {'name': 'DK', 'items': ['blue shell', 'star'], 'finish': 1}]

best_items(data_set)

{'green shell': 4, 'banana': 1, 'red shell': 1, 'blue shell': 1, 'star': 1}

In [111]:
def hand_count(hand):
    counts = []
    cards = {
        'A': 11,
        'J': 10,
        'Q': 10,
        'K': 10,
    }
    for h in hand:
        if h in cards:
            counts.append(cards[h])
        else:
            counts.append(int(h))
    if sum(counts) > 21:
        for i in range(len(counts)):
            if counts[i] == 11:
                counts[i] = 1
    return sum(counts)

def blackjack_hand_greater_than(hand_1, hand_2):
    if hand_count(hand_1) >  21:
        return False
    if hand_count(hand_2) > 21:
        return True
    return hand_count(hand_1) > hand_count(hand_2)

blackjack_hand_greater_than(['9'], ['9', 'Q', '8', 'A'])

True

In [ ]:
#Kaggle's solution
def hand_total(hand):
    total = 0
    # Count the number of aces and deal with how to apply them at the end.
    aces = 0
    for card in hand:
        if card in ['J', 'Q', 'K']:
            total += 10
        elif card == 'A':
            aces += 1
        else:
            # Convert number cards (e.g. '7') to ints
            total += int(card)
    # At this point, total is the sum of this hand's cards *not counting aces*.

    # Add aces, counting them as 1 for now. This is the smallest total we can make from this hand
    total += aces
    # "Upgrade" aces from 1 to 11 as long as it helps us get closer to 21
    # without busting
    while total + 10 <= 21 and aces > 0:
        # Upgrade an ace from 1 to 11
        total += 10
        aces -= 1
    return total

def blackjack_hand_greater_than(hand_1, hand_2):
    total_1 = hand_total(hand_1)
    total_2 = hand_total(hand_2)
    return total_1 <= 21 and (total_1 > total_2 or total_2 > 21)